language: rust
rust:
    - stable
    - beta
    - nightly
addons:
    apt:
        sources:
            - sourceline: "ppa:zfs-native/daily"
        packages:
            - ubuntu-zfs

matrix:
    allow_failues:
        - rust: nightly
