on:
  push:
    branches-ignore:
      - '**.tmp'

name: test

jobs:
  test:
    env:
      ZFS_TEMPFS: tpool

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.48.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update

      - name: Install dependencies
        run: sudo apt install libzfslinux-dev zfsutils-linux

      - name: Setup test pool
        run: sudo ./zfs-core/test-prepare "${ZFS_TEMPFS}"

      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
